apiVersion: v1
kind: Service
metadata:
  name: tarantool-service
spec:
  type: NodePort
  selector:
    app: tarantool
  ports:
    - protocol: TCP
      port: 3301
      targetPort: 3301
      nodePort: 30001  

