apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarantool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarantool
  template:
    metadata:
      labels:
        app: tarantool
    spec:
      containers:
        - name: tarantool
          image: tarantool/tarantool:3
          ports:
            - containerPort: 3301

