apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tarantool
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tarantool
  template:
    metadata:
      labels:
        app: tarantool
    spec:
      containers:
        - name: tarantool
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}

